services:
  smart-brain-backend:
    container_name: Backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/Smart-Brain-Backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/Smart-Brain-Backend
      - /usr/src/Smart-Brain-Backend/node_modules
    depends_on:
      - postgres

  #postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
